Создание объекта по шаблону
htmlacademy-javascript/2081429-keksobooking-26 pull request #5
Opened 2022-06-23 15:15 UTC by SpartanAndrey

2022-06-24 15:47 UTC, craz3r requested changes

2022-06-24 15:47 UTC, craz3r commented on js/object-template.js
> +    const img = document.createElement('img');
Обрати внимание, что на момент заполнения объявления в разметке уже есть одна картинка 
`<img src="" class="popup__photo" width="45" height="40" alt="Фотография жилья">`
Ее нужно удалить перед тем как начать вставлять картинки из данных. Так же обрати внимание на размеры (40 на 40) тк сейчас вставленное изображение слишком большое

2022-06-24 15:47 UTC, craz3r commented on js/object-template.js
> +testInCanvas.appendChild(rentalListFragment);
Объединить код с 59 строки по 81 в функцию и экспортировать ее, чтобы потом импортировать не модуль целиком а только одну функцию

2022-06-25 11:11 UTC, SpartanAndrey commented on js/object-template.js
>  const createCapacitySentence = (roomNumber, guestNumber) => {
Обновил функцию, так как окончания у "комнат" для 5 и больше были неправильные. Непонятно из задания, какое ограничение по количеству, из-за этого приходится писать несколько условий.

2022-06-25 11:57 UTC, SpartanAndrey commented on js/object-template.js
> +    hideEmptyData(rentalAdElement);
Насколько оптимально добавлять класс hidden? Имеет ли смысл сразу удалять элемент?

2022-06-27 07:29 UTC, craz3r commented on js/object-template.js
> +    hideEmptyData(rentalAdElement);
По части производительности оптимальнее добавлять класс hidden, тк удаление и вставка элементов в DOM дерево - более ресурсозатратные операции

2022-06-27 07:29 UTC, merged